# Site settings
title: Minimini
email: your-email@domain.com
signoff: your-name
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/minimini/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
google_analytics: # Set Tracking ID of Google Analytics Account.

links:
    - name: About
      url: /minimini/about
    - name: GitHub
      url: https://github.com/mikkkee
      external: true
    - name: LinkedIn
      url: https://sg.linkedin.com/in/wangjianfeng
      external: true

highlighter: rouge

# Build settings
markdown: kramdown
